import '../globals.css'
import type { Metadata } from 'next'
import DashboardHeader from '@/components/DashboardHeader'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: {children: React.ReactNode}) {
  const supabase = createServerComponentClient({ cookies });
  const {data} = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body>
        <DashboardHeader user={data.session?.user}/>
      
        {children}
      </body>
    </html>
  )
}
